package baic.device.service.dao.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Trace generated by hbm2java
 */
@Entity
@Table(name = "device_vehicle", catalog = "baic_device")
@NamedQueries(value = {
		@NamedQuery(name = DeviceVehicle.FIND_IMEI_BY_VEHICLE_ID, query = "SELECT dv.imei FROM DeviceVehicle dv WHERE dv.vehicleId = :vehicleId"),
		@NamedQuery(name = DeviceVehicle.FIND_VEHICLE_ID_BY_IMEI, query = "SELECT dv.vehicleId FROM DeviceVehicle dv WHERE dv.imei = :imei") })
public class DeviceVehicle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8011688407253968703L;

	public static final String FIND_IMEI_BY_VEHICLE_ID = "findImeiByVehicleId";
	public static final String FIND_VEHICLE_ID_BY_IMEI = "findVehicleIdByImei";

	private String imei;
	private Long vehicleId;

	public DeviceVehicle() {
	}

	public DeviceVehicle(String imei, Long vehicleId) {
		this.imei = imei;
		this.vehicleId = vehicleId;
	}

	@Id
	@Column(name = "imei", unique = true, nullable = false, length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "vehicle_id")
	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}
}
