package cn.concar.service.db.bean;

// Generated 2015-10-13 15:43:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "config", catalog = "baic_vs")
public class Config implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -24355801752443342L;

	private String configName;
	private String configValue;

	public Config() {
	}

	public Config(String configName, String configValue) {
		this.configName = configName;
		this.configValue = configValue;
	}

	@Id
	@Column(name = "config_name", unique = true, nullable = false, length = 45)
	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	@Column(name = "config_value", length = 45)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

}
