package cn.concar.service.db.bean;

// Generated 2015-10-13 15:43:18 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name = "device", catalog = "baic_vs")
public class Device implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6210461969342402000L;
	
	private String imei;
	private String simNumber;

	public Device() {
	}

	public Device(String imei) {
		this.imei = imei;
	}

	public Device(String imei, String simNumber) {
		this.imei = imei;
		this.simNumber = simNumber;
	}

	@Id
	@Column(name = "imei", unique = true, nullable = false, length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "sim_number", length = 45)
	public String getSimNumber() {
		return this.simNumber;
	}

	public void setSimNumber(String simNumber) {
		this.simNumber = simNumber;
	}

}
