package cn.concar.service.db.bean;

// Generated 2015-10-13 15:43:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LatestRecord generated by hbm2java
 */
@Entity
@Table(name = "latest_record", catalog = "baic_vs")
public class LatestRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7813201567416722339L;

	private Long recordId;
	private String imei;
	private Date traceTime;
	private Double longitude;
	private Double latitude;
	private Integer altitude;
	private Double hdop;
	private Double vdop;
	private Long mileage;
	private Integer speed;
	private Integer rpm;
	private Integer temperature;
	private Double voltage;
	private Boolean engine;
	private String dtc;
	private Boolean location;

	public LatestRecord() {
	}

	public LatestRecord(String imei, Date traceTime, Double longitude, Double latitude, Integer altitude, Double hdop,
			Double vdop, Long mileage, Integer speed, Integer rpm, Integer temperature, Double voltage, Boolean engine,
			String dtc, Boolean location) {
		this.imei = imei;
		this.traceTime = traceTime;
		this.longitude = longitude;
		this.latitude = latitude;
		this.altitude = altitude;
		this.hdop = hdop;
		this.vdop = vdop;
		this.mileage = mileage;
		this.speed = speed;
		this.rpm = rpm;
		this.temperature = temperature;
		this.voltage = voltage;
		this.engine = engine;
		this.dtc = dtc;
		this.location = location;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "record_id", unique = true, nullable = false)
	public Long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "imei", length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "trace_time", length = 19)
	public Date getTraceTime() {
		return this.traceTime;
	}

	public void setTraceTime(Date traceTime) {
		this.traceTime = traceTime;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "altitude")
	public Integer getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Integer altitude) {
		this.altitude = altitude;
	}

	@Column(name = "hdop", precision = 22, scale = 0)
	public Double getHdop() {
		return this.hdop;
	}

	public void setHdop(Double hdop) {
		this.hdop = hdop;
	}

	@Column(name = "vdop", precision = 22, scale = 0)
	public Double getVdop() {
		return this.vdop;
	}

	public void setVdop(Double vdop) {
		this.vdop = vdop;
	}

	@Column(name = "mileage")
	public Long getMileage() {
		return this.mileage;
	}

	public void setMileage(Long mileage) {
		this.mileage = mileage;
	}

	@Column(name = "speed")
	public Integer getSpeed() {
		return this.speed;
	}

	public void setSpeed(Integer speed) {
		this.speed = speed;
	}

	@Column(name = "rpm")
	public Integer getRpm() {
		return this.rpm;
	}

	public void setRpm(Integer rpm) {
		this.rpm = rpm;
	}

	@Column(name = "temperature")
	public Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(Integer temperature) {
		this.temperature = temperature;
	}

	@Column(name = "voltage", precision = 22, scale = 0)
	public Double getVoltage() {
		return this.voltage;
	}

	public void setVoltage(Double voltage) {
		this.voltage = voltage;
	}

	@Column(name = "engine")
	public Boolean getEngine() {
		return this.engine;
	}

	public void setEngine(Boolean engine) {
		this.engine = engine;
	}

	@Column(name = "dtc", length = 100)
	public String getDtc() {
		return this.dtc;
	}

	public void setDtc(String dtc) {
		this.dtc = dtc;
	}

	@Column(name = "location")
	public Boolean getLocation() {
		return this.location;
	}

	public void setLocation(Boolean location) {
		this.location = location;
	}

}
