package cn.concar.service.db.bean;

// Generated 2015-10-13 15:43:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trace generated by hbm2java
 */
@Entity
@Table(name = "trace", catalog = "baic_vs")
public class Trace implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8011688407253968703L;
	
	private Long traceId;
	private String imei;
	private Date traceDate;
	private String traceLine;

	public Trace() {
	}

	public Trace(String imei, Date traceDate, String traceLine) {
		this.imei = imei;
		this.traceDate = traceDate;
		this.traceLine = traceLine;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "trace_id", unique = true, nullable = false)
	public Long getTraceId() {
		return this.traceId;
	}

	public void setTraceId(Long traceId) {
		this.traceId = traceId;
	}

	@Column(name = "imei", length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "trace_date", length = 10)
	public Date getTraceDate() {
		return this.traceDate;
	}

	public void setTraceDate(Date traceDate) {
		this.traceDate = traceDate;
	}

	@Column(name = "trace_line", length = 65535)
	public String getTraceLine() {
		return this.traceLine;
	}

	public void setTraceLine(String traceLine) {
		this.traceLine = traceLine;
	}

}
