package baic.base.service.dao.bean;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "baic_base")
@NamedQueries(value = {
		@NamedQuery(name = Vehicle.FIND_VEHICLE_BY_DEPARTMENT_ID, query = "FROM Vehicle v WHERE v.belongDepartment = :departmentId"),
		@NamedQuery(name = Vehicle.FIND_VEHICLE_BY_DEPARTMENT_IDS, query = "FROM Vehicle v WHERE v.belongDepartment in (:idList)"),
		@NamedQuery(name = Vehicle.COUNT_VEHICLE_BY_DEPARTMENT_IDS, query = "SELECT COUNT(*), v.belongDepartment FROM Vehicle v GROUP BY v.belongDepartment"), })
public class Vehicle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4824198897062470501L;
	public static final String FIND_VEHICLE_BY_DEPARTMENT_ID = "findVehicleByDepartmentId";
	public static final String FIND_VEHICLE_BY_DEPARTMENT_IDS = "findVehicleByDepartmentIds";
	public static final String COUNT_VEHICLE_BY_DEPARTMENT_IDS = "countVehicleByDepartmentIds";

	private Long vehicleId;
	private String plateNumber;
	private String vin;
	private String model;
	private Double displacement;
	private String color;
	private Double mileage;
	private Date registeredDate;
	private Boolean valid;
	private Boolean sameName;
	private Integer keyNumber;
	private Boolean license;
	private Boolean certificate;
	private Boolean purchase;
	private Boolean tax;
	private Boolean clivta;
	private Date clivtaDate;
	private Boolean insurance;
	private Date insuranceDate;
	private Date inspectionDate;
	private Boolean violation;
	private Long belongDepartment;

	public Vehicle() {
	}

	public Vehicle(String plateNumber, String vin, String model, Double displacement, String color, Double mileage,
			Date registeredDate, Boolean valid, Boolean sameName, Integer keyNumber, Boolean license,
			Boolean certificate, Boolean purchase, Boolean tax, Boolean clivta, Date clivtaDate, Boolean insurance,
			Date insuranceDate, Date inspectionDate, Boolean violation, Long belongDepartment) {
		this.plateNumber = plateNumber;
		this.vin = vin;
		this.model = model;
		this.displacement = displacement;
		this.color = color;
		this.mileage = mileage;
		this.registeredDate = registeredDate;
		this.valid = valid;
		this.sameName = sameName;
		this.keyNumber = keyNumber;
		this.license = license;
		this.certificate = certificate;
		this.purchase = purchase;
		this.tax = tax;
		this.clivta = clivta;
		this.clivtaDate = clivtaDate;
		this.insurance = insurance;
		this.insuranceDate = insuranceDate;
		this.inspectionDate = inspectionDate;
		this.violation = violation;
		this.belongDepartment = belongDepartment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vehicle_id", unique = true, nullable = false)
	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "plate_number", length = 45)
	public String getPlateNumber() {
		return this.plateNumber;
	}

	public void setPlateNumber(String plateNumber) {
		this.plateNumber = plateNumber;
	}

	@Column(name = "vin", length = 45)
	public String getVin() {
		return this.vin;
	}

	public void setVin(String vin) {
		this.vin = vin;
	}

	@Column(name = "model", length = 45)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "displacement", precision = 22, scale = 0)
	public Double getDisplacement() {
		return this.displacement;
	}

	public void setDisplacement(Double displacement) {
		this.displacement = displacement;
	}

	@Column(name = "color", length = 45)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "mileage", precision = 22, scale = 0)
	public Double getMileage() {
		return this.mileage;
	}

	public void setMileage(Double mileage) {
		this.mileage = mileage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "registered_date", length = 10)
	public Date getRegisteredDate() {
		return this.registeredDate;
	}

	public void setRegisteredDate(Date registeredDate) {
		this.registeredDate = registeredDate;
	}

	@Column(name = "valid")
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@Column(name = "same_name")
	public Boolean getSameName() {
		return this.sameName;
	}

	public void setSameName(Boolean sameName) {
		this.sameName = sameName;
	}

	@Column(name = "key_number")
	public Integer getKeyNumber() {
		return this.keyNumber;
	}

	public void setKeyNumber(Integer keyNumber) {
		this.keyNumber = keyNumber;
	}

	@Column(name = "license")
	public Boolean getLicense() {
		return this.license;
	}

	public void setLicense(Boolean license) {
		this.license = license;
	}

	@Column(name = "certificate")
	public Boolean getCertificate() {
		return this.certificate;
	}

	public void setCertificate(Boolean certificate) {
		this.certificate = certificate;
	}

	@Column(name = "purchase")
	public Boolean getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Boolean purchase) {
		this.purchase = purchase;
	}

	@Column(name = "tax")
	public Boolean getTax() {
		return this.tax;
	}

	public void setTax(Boolean tax) {
		this.tax = tax;
	}

	@Column(name = "clivta")
	public Boolean getClivta() {
		return this.clivta;
	}

	public void setClivta(Boolean clivta) {
		this.clivta = clivta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "clivta_date", length = 10)
	public Date getClivtaDate() {
		return this.clivtaDate;
	}

	public void setClivtaDate(Date clivtaDate) {
		this.clivtaDate = clivtaDate;
	}

	@Column(name = "insurance")
	public Boolean getInsurance() {
		return this.insurance;
	}

	public void setInsurance(Boolean insurance) {
		this.insurance = insurance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "insurance_date", length = 10)
	public Date getInsuranceDate() {
		return this.insuranceDate;
	}

	public void setInsuranceDate(Date insuranceDate) {
		this.insuranceDate = insuranceDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inspection_date", length = 10)
	public Date getInspectionDate() {
		return this.inspectionDate;
	}

	public void setInspectionDate(Date inspectionDate) {
		this.inspectionDate = inspectionDate;
	}

	@Column(name = "violation")
	public Boolean getViolation() {
		return this.violation;
	}

	public void setViolation(Boolean violation) {
		this.violation = violation;
	}

	@Column(name = "belong_department")
	public Long getBelongDepartment() {
		return belongDepartment;
	}

	public void setBelongDepartment(Long belongDepartment) {
		this.belongDepartment = belongDepartment;
	}

}
